# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator.USER-20211001ZA\Desktop\projects\adsfoot\mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1152, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 520, 75, 23))
        self.pushButton.setObjectName("pushButton")
        
        self.importAddressBtn = QtWidgets.QPushButton(self.centralwidget)
        self.importAddressBtn.setGeometry(QtCore.QRect(120, 520, 110, 23))
        self.importAddressBtn.setObjectName("importAddress")
        
        self.clearWidgetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearWidgetBtn.setGeometry(QtCore.QRect(245, 520, 90, 23))
        self.clearWidgetBtn.setObjectName("clearWidget")
        
        self.premintImportBtn = QtWidgets.QPushButton(self.centralwidget)
        self.premintImportBtn.setGeometry(QtCore.QRect(350, 520, 110, 23))
        self.premintImportBtn.setObjectName("premintImport")
        
        self.premintDcAndTwitterBtn = QtWidgets.QPushButton(self.centralwidget)
        self.premintDcAndTwitterBtn.setGeometry(QtCore.QRect(475, 520, 125, 23))
        self.premintDcAndTwitterBtn.setObjectName("premintDcAndTwitter")
                
        self.twitterTaskImportBtn = QtWidgets.QPushButton(self.centralwidget)
        self.twitterTaskImportBtn.setGeometry(QtCore.QRect(615, 520, 125, 23))
        self.twitterTaskImportBtn.setObjectName("twitterTaskImport")
        
        
        self.twitterDailyCheckBtn = QtWidgets.QPushButton(self.centralwidget)
        self.twitterDailyCheckBtn.setGeometry(QtCore.QRect(755, 520, 100, 23))
        self.twitterDailyCheckBtn.setObjectName("twitterDailyCheck")
        
        self.twitterTaskBtn = QtWidgets.QPushButton(self.centralwidget)
        self.twitterTaskBtn.setGeometry(QtCore.QRect(875, 520, 125, 23))
        self.twitterTaskBtn.setObjectName("twitterTask")
        
        self.premintTaskImportBtn = QtWidgets.QPushButton(self.centralwidget)
        self.premintTaskImportBtn.setGeometry(QtCore.QRect(30, 545, 125, 23))
        self.premintTaskImportBtn.setObjectName("premintTaskImport")
        
        self.premintTaskBtn = QtWidgets.QPushButton(self.centralwidget)
        self.premintTaskBtn.setGeometry(QtCore.QRect(170, 545, 125, 23))
        self.premintTaskBtn.setObjectName("premintTask")
        
        self.premintCheckBtn = QtWidgets.QPushButton(self.centralwidget)
        self.premintCheckBtn.setGeometry(QtCore.QRect(310, 545, 125, 23))
        self.premintCheckBtn.setObjectName("premintCheck")
        
        
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 0, 1131, 500))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1152, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        
        self.pushButton.clicked.connect(self.showFileDialog)
        self.importAddressBtn.clicked.connect(self.importAddress)
        self.clearWidgetBtn.clicked.connect(self.clearWidget)
        self.premintImportBtn.clicked.connect(self.premintImport)
        self.premintDcAndTwitterBtn.clicked.connect(self.premintDcAndTwitter)
        self.twitterTaskImportBtn.clicked.connect(self.twitterTaskImport)
        self.twitterTaskBtn.clicked.connect(self.twitterTask)
        self.twitterDailyCheckBtn.clicked.connect(self.twitterDailyCheck)
        self.premintTaskImportBtn.clicked.connect(self.premintTaskImport)
        self.premintTaskBtn.clicked.connect(self.premintTask)
        self.premintCheckBtn.clicked.connect(self.premintCheck)
        
        
        
        
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "主窗口"))
        self.pushButton.setText(_translate("MainWindow", "导入数据"))
        self.importAddressBtn.setText(_translate("MainWindow", "导入metamask地址"))
        self.clearWidgetBtn.setText(_translate("MainWindow", "清除表格数据"))
        self.premintImportBtn.setText(_translate("MainWindow", "premint地址绑定"))
        self.premintDcAndTwitterBtn.setText(_translate("MainWindow", "premint推特和dc绑定"))
        self.twitterTaskImportBtn.setText(_translate("MainWindow", "推特任务数据导入"))
        self.twitterDailyCheckBtn.setText(_translate("MainWindow", "推特日常检查"))
        self.twitterTaskBtn.setText(_translate("MainWindow", "推特任务执行"))
        self.premintTaskImportBtn.setText(_translate("MainWindow", "premint任务数据导入"))
        self.premintTaskBtn.setText(_translate("MainWindow", "premint任务执行"))
        self.premintCheckBtn.setText(_translate("MainWindow", "premint任务检查"))
        

        
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "地址"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "账号id"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "助记词"))
        